blog/urls.py
from django.urls import path
from . import views
app_name ='blog'

urlpatterns =[
    path('index/',views.index, name = "index"),
    path('base/<spk>', views.base, name = "base" ),
    path('blogs_form/', views.blogs_form, name = "blogs_form"),
    path('delete/<int:spk>/', views.delete, name='delete'),
    path('blogs_update/<int:spk>/', views.blogs_update, name='blogs_update'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', views.index, name='index'), 
    path('blog/', include('blog.urls')),
    
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    author = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self):
        return self.subject

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']

blog/views.py
from django.shortcuts import render,redirect

# Create your views here.
from .models import Post

def index(request):
    posts = Post.objects.all()
    return render(request, 'index.html', {'posts': posts})


def base(request, spk):
    s = Post.objects.get(id = spk)
    context = {
        "s":s,
    }
    return render(request, "blog/base.html",context)

def blogs_form(request):
    if request.method == "POST":
        t = request.POST.get("title")
        c = request.POST.get("content")
        a = request.POST.get("author")
        Post(title= t, content = c, author = a).save()
        return redirect("index")
    return render( request, "blog/blogs_form.html")

def blogs_update(request, spk):
    s = Post.objects.get(id = spk)
    if request.method == "POST":
        t = request.POST.get("title")
        c = request.POST.get("content")
        print(c)
        a = request.POST.get("author")
        s.title,s.content,s.author = t,c,a
        s.save()
        return redirect("index")
    context = {
        "s": s
    }
    return render(request,"blog/blogs_update.html",context)



def delete (request, spk):
    s = Post.objects.get(id = spk)
    s.delete()
    return redirect("index")

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>My Blog - {% block title %}{% endblock %}</title>
</head>
<body>
    <nav>
        django blog nav bar
        <br>
    </nav>
    <div class="blog__content">
        {% block content %}
        {% endblock %}
        <br>
        <h1>django 게시물 구현 base.html </h1>
    </div>
</body>
</html>

templates/blog/blogs_form.html
{% extends 'base.html' %}

{% block title %} 글 입력 {% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <br>
    <h1>Post 입력 화면</h1>
    <hr>
    <label for="title">제목:</label>
    <input type="text" name="title" required><br><br>

    <label for="content">내용:</label>
    <textarea name="content" required></textarea><br><br>

    <label for="author">작성자:</label>
    <input type="text" name="author" required><br><br>

    <input type="submit" value="작성하기">
</form>
{% endblock %}

templates/blog/blogs_update.html
{% extends 'base.html' %}

{% block title %} 글 입력 {% endblock %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <br>
    <h1>Post 입력 화면</h1>
    <hr>
    <label for="title">제목:</label>
    <input type="text" name="title" value="{{s.title}}" required><br><br>

    <label for="content">내용:</label>
    <textarea name="content" value="{{s.content}}" required></textarea><br><br>

    <label for="author">작성자:</label>
    <input type="text" name="author" value="{{s.author}}" required><br><br>

    <input type="submit" value="수정하기">
</form>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
<link rel ="stylesheet" href= "../static/css/index.css">
{% block title %}Main(index.html){% endblock %}

{% block content %}
<br>
<a href="{% url 'blog:blogs_form' %}"><button>게시글 생성</button></a>
<hr>


    {% for post in posts %}
    <a href="{% url 'blog:delete' spk=post.id %}"><button>DEL</button></a>
    <a href="{% url 'blog:blogs_update' spk=post.id %}"><button>UPDATE</button></a>
<br>
<br>
    <h1>{{ post.title }}</h1>
    <br>
        <p>{{ post.content }}</p>
        <p>Written by: {{ post.author }}</p>
        <p>Created at: {{ post.created_at }}</p>
        <br>
        <hr>
    {% endfor %}
    <h1>index.html main page입니다</h1>
    {% endblock %}


    